version: '3.8'

services:
  mongodb:
    image: mongo:4.4.3
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./mongo/data/restaurant.json:/docker-entrypoint-initdb.d/restaurant.json:ro
      - mongo-volume:/data/db
    restart: unless-stopped

  restaurantapi:
    build:
      context: .
      dockerfile: ./restaurantapi/Dockerfile
    container_name: restaurantapi
    hostname: restaurantapi
    environment:
      MONGO_URI: ${MONGO_URI}
    ports:
      - ${API_PORT}:8080
    restart: unless-stopped
    depends_on:
      - mongodb

volumes:
  mongo-volume:
