apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  labels:
    app: restaurant
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fstype: ext4
  zone: eu-west-2b
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
