apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: restaurant
spec:
  ports:
    - port: 27017
  selector:
    app: restaurant
    tier: mongodb
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    app: restaurant
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb-rc
  labels:
    app: restaurant
spec:
  replicas: 1
  selector:
      app: restaurant
      tier: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: restaurant
        tier: mongodb
    spec:                                                     
      containers:
        - name: mongodb
          image: mongo:4.4.3
          envFrom:
            - configMapRef:
                name: mongodb-config
            - secretRef:
                name: mongodb-secrets
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-persistent
              mountPath: /data/db
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: mongodb-persistent
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: initdb
          configMap:
            name: mongodb-init